# Generated by Django 4.2.5 on 2024-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="presenet_loc_latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="user",
            name="presenet_loc_longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
