# Generated by Django 4.2.5 on 2024-01-14 10:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_presenet_loc_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
