# Generated by Django 4.2.5 on 2024-04-23 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_servicerequest_rider_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
